from .dataCompile   import dataFormating
from .excelConv     import excelConv
from .feh2celConv   import feh2cel
from .lineRemove    import deleteLastLine
from .progressBar   import loadBar
from .sendEmail     import sendMail
from .weatherData   import getWeather
from .locationData  import get_location_ip
from .graphicRep    import plot_forcast_data